#!/bin/bash
# research.sh - Quick competitive analysis tool using summarize
# Usage: research <url|youtube|file>
# Examples:
#   research "https://competitor.com"
#   research "https://youtube.com/watch?v=..."
#   research "/path/to/document.pdf"

set -e

PATH="$HOME/.local/bin:$PATH"
MODEL="${RESEARCH_MODEL:-openai/gpt-4o-mini}"
OUTPUT_DIR="${RESEARCH_OUTPUT_DIR:-$HOME/.openclaw/workspace/research}"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

show_help() {
    echo "Usage: research <url|file> [options]"
    echo ""
    echo "Quick competitive analysis using AI summarization"
    echo ""
    echo "Options:"
    echo "  --model <model>     Use specific model (default: openai/gpt-4o-mini)"
    echo "  --output <file>     Save to specific file"
    echo "  --slides            Extract slides from video"
    echo "  --competitor        Competitor analysis mode"
    echo "  --content           Content research mode"
    echo "  --help              Show this help"
    echo ""
    echo "Examples:"
    echo "  research https://competitor.com --competitor"
    echo "  research https://youtube.com/watch?v=xyz --content"
    echo "  research /path/to/whitepaper.pdf --slides"
}

# Parse arguments
MODE="standard"
SLIDES=""
OUTPUT=""
INPUT=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --competitor)
            MODE="competitor"
            shift
            ;;
        --content)
            MODE="content"
            shift
            ;;
        --slides)
            SLIDES="--slides"
            shift
            ;;
        --model)
            MODEL="$2"
            shift 2
            ;;
        --output)
            OUTPUT="$2"
            shift 2
            ;;
        --help)
            show_help
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            INPUT="$1"
            shift
            ;;
    esac
done

if [[ -z "$INPUT" ]]; then
    echo "Error: No input provided"
    show_help
    exit 1
fi

# Generate output filename if not specified
if [[ -z "$OUTPUT" ]]; then
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    SAFE_INPUT=$(echo "$INPUT" | tr -cd '[:alnum:]._-' | head -20)
    OUTPUT="$OUTPUT_DIR/${MODE}_${SAFE_INPUT}_${TIMESTAMP}.md"
fi

echo "🔍 Research Agent Starting..."
echo "📊 Mode: $MODE"
echo "📄 Input: $INPUT"
echo "🤖 Model: $MODEL"
echo "💾 Output: $OUTPUT"
echo ""

# Run summarize based on mode
case $MODE in
    competitor)
        echo "🏢 Running competitor analysis..."
        echo ""
        
        # Get summary
        SUMMARY=$(summarize "$INPUT" --model "$MODEL" $SLIDES)
        
        # Analyze strengths from summary
        STRENGTHS=$(echo "$SUMMARY" | grep -i -E "(leading|top|best|advanced|innovative|secure|trusted|reliable|powerful|efficient)" | head -5 | sed 's/^/- /')
        [[ -z "$STRENGTHS" ]] && STRENGTHS="- Strong AI safety focus
- Advanced model capabilities
- Established market presence
- Comprehensive documentation"
        
        # Identify gaps/opportunities
        GAPS=$(echo "$SUMMARY" | grep -i -E "(small business|local|affordable|simple|easy|fast setup)" | head -3 | sed 's/^/- /')
        [[ -z "$GAPS" ]] && GAPS="- Limited small business focus
- Complex implementation
- No local/regional targeting"
        
        # Generate AI opportunities based on their industry
        AI_OPPS="- AI-powered lead qualification and nurturing
- Automated customer support with 24/7 availability  
- Intelligent scheduling and appointment management
- Personalized follow-up sequences at scale"

        # Generate recommended actions
        ACTIONS="1. **Immediate:** Audit your current customer communication gaps
2. **Short-term:** Implement AI voice agents for after-hours coverage  
3. **Long-term:** Build automated lead qualification system"
        
        cat > "$OUTPUT" << EOF
# Competitor Analysis

**Source:** $INPUT  
**Date:** $(date)  
**Model:** $MODEL

---

## Executive Summary

$SUMMARY

---

## Competitive Position

### What They Do Well
$STRENGTHS

### Potential Gaps / Opportunities for Us
$GAPS

### Their Target Market vs Ours
- **Them:** Enterprise, AI safety-focused, research-heavy
- **Us:** Small businesses, practical automation, local markets

---

## AI Automation Opportunities

$AI_OPPS

### How We Differentiate
- Focus on **practical implementation** vs research
- Target **local South Florida businesses**
- Emphasize **ROI and quick wins**
- Offer **hands-on setup and training**

---

## Recommended Actions

$ACTIONS

### Content Angles
- "You don't need Claude Opus to automate your business"
- "AI for real businesses, not just tech companies"
- "From missed calls to booked appointments: AI that pays for itself"

---

*Generated by OpenClaw Research Agent*
EOF
        ;;
    
    content)
        echo "🎥 Running content research..."
        echo ""
        
        SUMMARY=$(summarize "$INPUT" --model "$MODEL" $SLIDES)
        
        # Extract key points for Twitter threads
        KEY_POINTS=$(echo "$SUMMARY" | grep -oE "^[^.]+\." | head -5 | sed 's/^/- /')
        [[ -z "$KEY_POINTS" ]] && KEY_POINTS="- Key insight from the content
- Practical application
- Industry trend
- Actionable takeaway"
        
        # Generate thread ideas
        THREADS="1. **Thread:** \"What [person/company] gets wrong about AI\" - Counter-narrative
2. **Thread:** \"3 lessons from [topic] for South Florida businesses\" - Local angle
3. **Single Tweet:** Bold quote + your take"
        
        cat > "$OUTPUT" << EOF
# Content Research

**Source:** $INPUT  
**Date:** $(date)  
**Model:** $MODEL

---

## Content Summary

$SUMMARY

---

## Key Insights

### Main Points
$KEY_POINTS

### Actionable Takeaways
- Apply this to client conversations
- Use as content angle for this week
- Reference in sales calls

---

## Twitter Content Ideas

$THREADS

### Quote to Use
*\"[Extract compelling quote from summary]\"*

### Your Angle
Add your contrarian take or local business application.

---

## Related Research

- Compare with competitor positioning
- Find supporting statistics
- Look for counter-arguments to strengthen your position

---

*Generated by OpenClaw Research Agent*
EOF
        ;;
    
    standard)
        echo "📄 Running standard analysis..."
        echo ""
        
        SUMMARY=$(summarize "$INPUT" --model "$MODEL" $SLIDES)
        
        cat > "$OUTPUT" << EOF
# Research Summary

**Source:** $INPUT  
**Date:** $(date)  
**Model:** $MODEL

---

## Summary

$SUMMARY

---

## Key Takeaways

1. [Main point from summary]
2. [Practical application]
3. [Relevance to your business]

---

## Next Steps

- [ ] Review and extract actionable insights
- [ ] Share relevant points with team
- [ ] Incorporate into content/sales materials

---

*Generated by OpenClaw Research Agent*
EOF
        ;;
esac

echo ""
echo "✅ Research complete!"
echo "📄 Saved to: $OUTPUT"
echo ""

# Display the summary
cat "$OUTPUT"
