#!/bin/bash
# Setup Make.com (Integromat) Automation for Etsy

echo "=== ETSY AUTOMATION SETUP ==="
echo ""
echo "This guide will connect Etsy to your workflow"
echo ""
echo "STEP 1: Create Make.com account"
echo "  - Go to: https://www.make.com"
echo "  - Sign up with: akennedy@theonegroup.info"
echo "  - Choose Free plan (1,000 operations/month)"
echo ""
echo "STEP 2: Create New Scenario"
echo "  - Click 'Create a new scenario'"
echo "  - Search for 'Etsy' trigger"
echo "  - Select 'Watch New Order'"
echo ""
echo "STEP 3: Connect Etsy"
echo "  - Click 'Add' to create connection"
echo "  - Login to Etsy when prompted"
echo "  - Authorize Make.com access"
echo ""
echo "STEP 4: Add Google Sheets Module"
echo "  - Add module: Google Sheets > Add Row"
echo "  - Connect Google account"
echo "  - Create new spreadsheet: 'LaserPecker Orders'"
echo "  - Columns: Date | Order ID | Customer | SKU | Personalization | Status | Ship By"
echo ""
echo "STEP 5: Add Gmail Module"
echo "  - Add module: Gmail > Send Email"
echo "  - Use template from: email_templates/proof_request.txt"
echo "  - Map variables: {customer_name}, {order_id}, etc."
echo ""
echo "STEP 6: Schedule"
echo "  - Set trigger: Every 15 minutes"
echo "  - Turn ON scenario"
echo ""
echo "STEP 7: Test"
echo "  - Create test order in Etsy"
echo "  - Verify row appears in Google Sheets"
echo "  - Verify email is sent"
echo ""
echo "=== COST ==="
echo "Make Free: 1,000 operations/month"
echo "Typical usage: ~500 ops/month (plenty of headroom)"
echo ""
echo "=== FILES READY ==="
ls -la ~/.openclaw/workspace/etsy-automation/
