#!/usr/bin/env bash
# sync_model_routing.sh — regenerate MODEL_ROUTING_V2.json + MODEL_ROUTING.md
# from the canonical routing-config.json (v5.2 schema).
#
# v5.2 schema (2026-08-01+): .version, .stack{primary,fallback1-3,utility,local_batch},
# .retired_*_*, .health_checks. This replaces the old v4 fields
# (.routing.task_classes / .routing.provider_failover / .safety.exclude_models) that
# no longer exist and caused jq null errors (paid_chain). Fixed 2026-08-12.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANONICAL="$ROOT_DIR/routing-config.json"
V2_OUT="$ROOT_DIR/MODEL_ROUTING_V2.json"
MD_OUT="$ROOT_DIR/MODEL_ROUTING.md"
RUNTIME_SYNC="$ROOT_DIR/scripts/sync_model_runtime_config.mjs"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required for sync_model_routing.sh" >&2
  exit 1
fi

# Validate JSON.
jq empty "$CANONICAL"

# ---- MODEL_ROUTING_V2.json (v5.2 schema) ------------------------------------
jq '{
  model_routing: {
    canonical_source: "routing-config.json",
    version: .version,
    updated: .updated,
    policy: "Cost first, quality guarded. Use free Ollama Cloud models by default and escalate through paid fallbacks only when they fail.",
    stack: {
      primary: .stack.primary,
      fallback1: .stack.fallback1,
      fallback2: .stack.fallback2,
      fallback3: .stack.fallback3,
      utility: .stack.utility,
      local_batch: .stack.local_batch
    },
    retired: .retired_2026_07_31,
    health: {
      enabled: .health_checks.enabled,
      frequency: .health_checks.frequency,
      check_models: .health_checks.check_models,
      cloud_api_models: .health_checks.cloud_api_models,
      state_file: .health_checks.track_file
    }
  }
}' "$CANONICAL" > "$V2_OUT"

# ---- MODEL_ROUTING.md -------------------------------------------------------
VERSION="$(jq -r '.version' "$CANONICAL")"
UPDATED="$(jq -r '.updated' "$CANONICAL")"
PRIMARY="$(jq -r '.stack.primary.model' "$CANONICAL")"
PRIMARY_NOTE="$(jq -r '.stack.primary.note // empty' "$CANONICAL")"
FALLBACK1="$(jq -r '.stack.fallback1.model' "$CANONICAL")"
FALLBACK2="$(jq -r '.stack.fallback2.model' "$CANONICAL")"
FALLBACK3="$(jq -r '.stack.fallback3.model' "$CANONICAL")"
UTILITY="$(jq -r '.stack.utility.model' "$CANONICAL")"
LOCAL_BATCH="$(jq -r '.stack.local_batch.models[]' "$CANONICAL" | tr '\n' ' ')"
CHECK_MODELS="$(jq -r '.health_checks.check_models[]' "$CANONICAL" | tr '\n' ' ')"
CLOUD_MODELS="$(jq -r '.health_checks.cloud_api_models[]' "$CANONICAL" | tr '\n' ' ')"
RETIRED="$(jq -r '.retired_2026_07_31[]' "$CANONICAL" | nl -w1 -s'. `')"

cat > "$MD_OUT" <<MD
# Model Routing & Cost Rules

**Canonical Source:** \`routing-config.json\`  
**Version:** ${VERSION} (updated ${UPDATED})

## Core Policy

Cost first, quality guarded. Use the free Ollama Cloud models by default; escalate through paid fallbacks only when the free models are unavailable.

- **Primary (all interactive sessions, crons, heartbeats):** \`${PRIMARY}\`
  ${PRIMARY_NOTE:+  - ${PRIMARY_NOTE}}
- **Fallback 1:** \`${FALLBACK1}\` (auto-fallback if primary is down)
- **Fallback 2:** \`${FALLBACK2}\` (when both Ollama models fail)
- **Fallback 3:** \`${FALLBACK3}\` (second paid fallback)
- **Utility (last-resort emergency):** \`${UTILITY}\`
- **Local batch (direct API from scripts — Arlo, Iris):** ${LOCAL_BATCH}

## Canonical Configuration

- All authoritative routing rules live in \`routing-config.json\`.
- \`MODEL_ROUTING_V2.json\` and this file are generated by:
  - \`bash scripts/sync_model_routing.sh\`

## Health Monitoring

- Daily smoke checks for core models: \`${CHECK_MODELS}\`
- Cloud API models to balance: \`${CLOUD_MODELS}\`
- Command: \`bash scripts/model_routing_healthcheck.sh\`
- Full OpenClaw canary: \`bash scripts/model_routing_canary.sh\`
- Provider balance check: \`bash scripts/model_provider_balance_check.sh\`
- State file: \`memory/heartbeat-state.json\`

## Retired / Dead Models

$(sed 's/$/`/' <<<"$RETIRED")
MD

if [[ -f "$RUNTIME_SYNC" ]]; then
  node "$RUNTIME_SYNC"
fi

echo "Synced: $V2_OUT and $MD_OUT from $CANONICAL"
