#!/bin/bash
# ============================================================
# weekly_maintenance.sh — Weekly Systems Audit + Cleanup
# Runs every week to keep everything managed & clean across
# The One Group / Pit Row Miami / all systems.
#
# Produces a status report at the end. Schedule via cron job.
# ============================================================
set -uo pipefail
cd "$HOME/.openclaw/workspace" || exit 1

REPORT="$HOME/.openclaw/workspace/reports/weekly_maintenance_report.md"
mkdir -p "$(dirname "$REPORT")"
TS=$(date '+%Y-%m-%d %H:%M %Z')
{
  echo "# 🧹 Weekly Systems Maintenance — $TS"
  echo ""
  echo "Generated by weekly_maintenance.sh (auto)."
  echo ""
} > "$REPORT"

# ---------- 1. LIVE SITE CHECK ----------
echo "## 🌐 Websites" >> "$REPORT"
for url in "https://theonegroup.info" "https://pitrowmiami.com"; do
  code=$(curl -s -o /dev/null -w "%{http_code}" -m 15 "$url")
  echo "- $url → HTTP $code $([ "$code" = "200" ] && echo '✅' || echo '⚠️')" >> "$REPORT"
done
echo "" >> "$REPORT"

# ---------- 2. CRON HEALTH (via openclaw) ----------
echo "## ⏰ Cron Jobs" >> "$REPORT"
openclaw cron list 2>/dev/null >> "$REPORT" || echo "  (cron list unavailable)" >> "$REPORT"
echo "" >> "$REPORT"

# ---------- 3. SYSTEM PROCESSES ----------
echo "## ⚙️ Swarm / Webhook" >> "$REPORT"
if pgrep -f webhook_server.py > /dev/null; then
  echo "- webhook_server: RUNNING ✅" >> "$REPORT"
else
  echo "- webhook_server: NOT RUNNING ⚠️" >> "$REPORT"
fi
echo "" >> "$REPORT"

# ---------- 4. DISK / STRAY FILES ----------
echo "## 💾 Workspace" >> "$REPORT"
du -sh "$HOME/.openclaw/workspace" 2>/dev/null | awk '{print "- Workspace size: " $1}' >> "$REPORT"
# Find loose files at workspace root (top-level non-dir, non-script clutter)
LOOSE=$(find "$HOME/.openclaw/workspace" -maxdepth 1 -type f -not -name '*.md' -not -name '*.py' -not -name '*.sh' -not -name '*.js' -not -name '*.json' -not -name '*.txt' 2>/dev/null | wc -l | tr -d ' ')
echo "- Loose files at workspace root: $LOOSE" >> "$REPORT"
echo "" >> "$REPORT"

echo "✅ Weekly maintenance scan complete. Full report: $REPORT" | tee -a "$REPORT"
