#!/usr/bin/env python3
"""
Generate Executive Summary Email for VP of Sales
Works with any Scout report type
"""

import json
import sys
from datetime import datetime
from pathlib import Path

def generate_vp_email(data_path=None):
    """Generate VP-level executive email"""
    
    # Load data
    if data_path is None:
        data_path = Path('/Users/aleckennedy/.openclaw/workspace/data/scout_output/bf_performance_latest.json')
    else:
        data_path = Path(data_path)
    
    if not data_path.exists():
        print(f"❌ Data file not found: {data_path}")
        return None
    
    with open(data_path) as f:
        data = json.load(f)
    
    # Detect report type
    report_type = detect_report_type(data)
    
    if report_type == 'bf_performance':
        return generate_bf_email(data)
    elif report_type == 'field_activity':
        return generate_field_email(data)
    elif report_type == 'sales':
        return generate_sales_email(data)
    else:
        return generate_generic_email(data)

def detect_report_type(data):
    """Auto-detect report type"""
    if 'top_performers' in data and 'needs_help' in data:
        if data.get('summary', {}).get('total_reps', 0) > 0:
            return 'bf_performance'
    if data.get('data_type') == 'field_activity':
        return 'field_activity'
    if data.get('data_type') == 'sales':
        return 'sales'
    return 'generic'

def generate_bf_email(data):
    """Generate email for Brown Forman rep performance"""
    summary = data['summary']
    today = datetime.now().strftime('%A, %B %d, %Y')
    
    # Calculate key metrics
    team_pct = summary['team_pct_goal'] * 100
    gap = summary['total_goal'] - summary['total_new_pod']
    
    # Find critical issues
    worst_performers = data['needs_help'][:5]
    
    # Generate recommendations
    recommendations = []
    
    if team_pct < 80:
        recommendations.append(f"🚨 URGENT: Team at {team_pct:.0f}% of goal. Need {gap:.0f} new POD to hit target.")
    elif team_pct < 90:
        recommendations.append(f"⚠️ Team at {team_pct:.0f}% of goal. {gap:.0f} new POD needed. Focus on middle performers.")
    else:
        recommendations.append(f"✅ Team at {team_pct:.0f}% of goal. {gap:.0f} new POD to close. Strong finish possible.")
    
    if worst_performers:
        recommendations.append(f"👥 {len(worst_performers)} reps significantly behind - immediate coaching required.")
        recommendations.append(f"   Lowest: {worst_performers[0]['rep_name']} ({worst_performers[0].get('pct_goal', 0)*100:.0f}% to goal)")
    
    recommendations.append(f"💰 ${summary['total_payout']:,.0f} paid in incentives. Review ROI on underperformers.")
    
    if summary['behind'] > 10:
        recommendations.append(f"📞 Schedule 1:1s with bottom {min(summary['behind'], 10)} performers this week.")
    
    # Build email
    email = f"""Subject: Daily Scout Brief - {today}

EXECUTIVE SUMMARY
================
Program: Road to Cinco Q4 H&R
Team Size: {summary['total_reps']} reps
Performance: {summary['total_new_pod']:.0f} / {summary['total_goal']:.0f} new POD ({team_pct:.1f}% to goal)
Status: {'🚨 Behind' if team_pct < 80 else '⚠️ At Risk' if team_pct < 90 else '✅ On Track'}

KEY METRICS
-----------
• Total Payouts: ${summary['total_payout']:,.0f}
• Reps Behind Goal: {summary['behind']} ({summary['behind']/summary['total_reps']*100:.0f}% of team)
• Gap to Close: {gap:.0f} new POD

TOP PERFORMERS
--------------
"""
    
    for i, r in enumerate(data['top_performers'][:3], 1):
        pct = r.get('pct_goal', 0) * 100
        email += f"{i}. {r['rep_name']}: {r.get('new_pod', 0):.0f} new POD ({pct:.0f}% to goal)\n"
    
    email += f"""
CRITICAL ATTENTION NEEDED
-------------------------
"""
    
    for r in worst_performers[:3]:
        pct = r.get('pct_goal', 0) * 100
        new_pod = r.get('new_pod', 0)
        goal = r.get('goal', 0)
        email += f"• {r['rep_name']}: {new_pod:.0f}/{goal:.0f} new POD ({pct:.0f}%)\n"
    
    email += f"""
ACTIONABLE RECOMMENDATIONS
--------------------------
"""
    for rec in recommendations:
        email += f"• {rec}\n"
    
    email += f"""
NEXT STEPS
----------
1. Review bottom {min(summary['behind'], 5)} performers for coaching
2. Check in with middle tier (80-99% of goal) for final push
3. Celebrate top performers to maintain momentum

Generated by Scout Sales Intelligence
{today}
"""
    
    return email

def generate_field_email(data):
    """Generate email for field activity/visit tracking"""
    summary = data['summary']
    today = datetime.now().strftime('%A, %B %d, %Y')
    
    email = f"""Subject: Daily Scout Brief - Field Activity Report ({today})

EXECUTIVE SUMMARY
================
Report Type: Field Visit Tracking
Total Accounts: {summary['total_accounts']}
Team Members: {summary.get('unique_reps', 'N/A')}

KEY METRICS
-----------
• Accounts Visited (30 days): {summary['active']}
• Hot Opportunities: {summary['hot']} 🔥
• Needs Visit (14+ days): {summary['needs_visit']} 📍
• At Risk (21+ days): {summary['at_risk']} 🚨
• Average Days Since Visit: {summary.get('avg_days_since_visit', 'N/A')}

INSIGHTS
--------
"""
    
    for insight in data.get('insights', [])[:5]:
        email += f"• {insight}\n"
    
    email += """
ACTIONABLE RECOMMENDATIONS
--------------------------
"""
    
    if summary['at_risk'] > 0:
        email += f"• 🚨 URGENT: {summary['at_risk']} accounts haven't been visited in 21+ days. Risk of churn.\n"
    
    if summary['needs_visit'] > 0:
        email += f"• 📍 {summary['needs_visit']} accounts due for routine visit. Schedule this week.\n"
    
    if summary['hot'] > 0:
        email += f"• 🔥 {summary['hot']} accounts showing high activity. Capitalize with promotions.\n"
    
    email += """
NEXT STEPS
----------
1. Prioritize at-risk accounts for immediate visits
2. Review route efficiency for field reps
3. Follow up on hot opportunities within 48 hours

Generated by Scout Sales Intelligence
"""
    
    return email

def generate_sales_email(data):
    """Generate email for traditional sales data"""
    summary = data['summary']
    today = datetime.now().strftime('%A, %B %d, %Y')
    
    email = f"""Subject: Daily Scout Brief - Sales Performance ({today})

EXECUTIVE SUMMARY
================
Total Accounts: {summary['total_accounts']}
Team Performance: {summary.get('team_pct_goal', 0)*100:.1f}% of goal

ACCOUNT HEALTH
--------------
• Exceeding Goal: {summary.get('excellent', 0)} 🔥
• On Track: {summary.get('active', 0)} ✅
• At Risk: {summary.get('at_risk', 0)} ⚠️
• Behind Goal: {summary.get('behind', 0)} 🚨

ACTION ITEMS
------------
"""
    
    if summary.get('behind', 0) > 0:
        email += f"• Contact {summary['behind']} accounts behind goal for retention offers\n"
    
    if summary.get('at_risk', 0) > 0:
        email += f"• URGENT: {summary['at_risk']} accounts at risk of churning\n"
    
    if summary.get('excellent', 0) > 0:
        email += f"• Upsell opportunities with {summary['excellent']} high-performing accounts\n"
    
    email += """
Generated by Scout Sales Intelligence
"""
    
    return email

def generate_generic_email(data):
    """Generate generic email for unknown data types"""
    today = datetime.now().strftime('%A, %B %d, %Y')
    
    return f"""Subject: Daily Scout Brief ({today})

EXECUTIVE SUMMARY
================
Your Scout analysis has been completed.

Please review the attached dashboard for detailed insights.

Generated by Scout Sales Intelligence
"""

def save_email(email_content, filename=None):
    """Save email to file"""
    if filename is None:
        today = datetime.now().strftime('%Y%m%d')
        filename = f'vp_email_{today}.txt'
    
    output_dir = Path('/Users/aleckennedy/.openclaw/workspace/data/scout_output')
    output_dir.mkdir(parents=True, exist_ok=True)
    
    output_path = output_dir / filename
    
    with open(output_path, 'w') as f:
        f.write(email_content)
    
    return output_path

def main():
    print("🎯 Scout - Generate VP Email")
    print("-" * 50)
    
    # Generate email
    email = generate_vp_email()
    
    if email:
        # Save to file
        output_path = save_email(email)
        
        print(f"✅ Email generated: {output_path}")
        print()
        print("=" * 60)
        print("EMAIL PREVIEW:")
        print("=" * 60)
        print()
        print(email)
        print()
        print("=" * 60)
        print()
        print(f"📧 Ready to send! File saved to:")
        print(f"   {output_path}")
        print()
        print("💡 Tip: Copy and paste into Gmail to send to your VP")
    else:
        print("❌ Failed to generate email")
        return 1
    
    return 0

if __name__ == "__main__":
    sys.exit(main())