#!/usr/bin/env python3
"""
Weekly Lead Report — reads the Google Sheet tracker + Arlo findings,
builds a leads->drafts->calls summary, and creates a Gmail DRAFT for Alec
to review (never sends automatically).
Run manually or via weekly cron (e.g. Mondays 8 AM).
"""
import json, urllib.request
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path

WS = Path("/Users/aleckennedy/.openclaw/workspace")
FINDINGS = WS / "data/arlo_findings.json"
API = "http://localhost:3000/v1/actions/"
SPREADSHEET_ID = "1NcLE13A6aLc2lAkw-5ch46Ydyx-1vabFUstZvBh9UDI"
SHEET_RANGE = "Sheet1!A:D"
ALEC = "akennedy@theonegroup.info"


def connector(action, payload, timeout=20):
    req = urllib.request.Request(
        API + action,
        data=json.dumps({"input": payload}).encode(),
        headers={"content-type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)


def create_draft(to, subject, body):
    resp = connector("gmail.create_draft", {"to": to, "subject": subject, "body": body}, timeout=30)
    return resp.get("success")


def main():
    # ---- Sheet data (source of truth for what got logged) ----
    sheet = connector("googlesheets.values_get", {
        "spreadsheetId": SPREADSHEET_ID, "range": SHEET_RANGE, "majorDimension": "ROWS"})
    rows = sheet.get("data", {}).get("values", []) if isinstance(sheet.get("data"), dict) else []
    if not rows:
        rows = sheet.get("values", [])  # tolerate either shape

    header, data_rows = (rows[0], rows[1:]) if rows else ([], [])
    week_ago = (datetime.now() - timedelta(days=6)).date()
    this_week = []
    for r in data_rows:
        try:
            d = datetime.strptime(str(r[0])[:10], "%Y-%m-%d").date()
        except Exception:
            continue
        if d >= week_ago:
            this_week.append(r)

    cities = Counter(r[3] for r in this_week if len(r) > 3 and r[3])
    industries = Counter(r[2] for r in this_week if len(r) > 2 and r[2])

    # ---- Pipeline state from Arlo/Iris ----
    try:
        findings = json.load(open(FINDINGS))
        leads = findings.get("leads", [])
    except Exception:
        leads = []
    drafted = sum(1 for l in leads if l.get("status") == "drafted")
    call_listed = sum(1 for l in leads if l.get("status") == "call_listed")
    scheduled = sum(1 for l in leads if l.get("calendar_event_at"))
    pending = sum(1 for l in leads if l.get("status") in ("new", "enriched"))

    today = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"WEEKLY LEAD REPORT — week of {today}",
        "",
        "FUNNEL (all time):",
        f"  Total leads in tracker:  {len(leads)}",
        f"  Email drafts created:    {drafted}",
        f"  Call-listed (phone):     {call_listed}",
        f"  Calendar calls booked:   {scheduled}",
        f"  Still pending outreach:  {pending}",
        "",
        f"THIS WEEK (sheet rows since {week_ago}): {len(this_week)} new leads logged",
        "",
        "  By city:",
    ]
    lines += [f"    {c}: {n}" for c, n in cities.most_common()] or ["    (none)"]
    lines += ["", "  By industry:"]
    lines += [f"    {i}: {n}" for i, n in industries.most_common()] or ["    (none)"]
    lines += [
        "",
        "NEXT ACTIONS:",
        "  1. Review Gmail drafts and send the good ones.",
        "  2. Work the calendar call blocks (15 min each, phone + opener in description).",
        "  3. Mark replies back in the sheet so conversion tracking stays honest.",
        "",
        "--",
        "Generated by Clawd (weekly_summary.py). Draft only — review before sending.",
    ]

    subject = f"📊 Weekly Lead Report — {today} ({len(this_week)} new leads)"
    if create_draft(ALEC, subject, "\n".join(lines)):
        print(f"✅ weekly report draft created: {subject}")
    else:
        print("❌ failed to create weekly report draft")


if __name__ == "__main__":
    main()
