#!/bin/bash
# The One Group Automation Setup Checklist

echo "==================================="
echo "THE ONE GROUP AUTOMATION SETUP"
echo "==================================="
echo ""
echo "STEP 1: Apollo.io (Lead Discovery)"
echo "  [ ] Go to https://www.apollo.io"
echo "  [ ] Create free account"
echo "  [ ] Search: Roofing companies in Fort Lauderdale, FL"
echo "  [ ] Filter: No website OR weak website"
echo "  [ ] Export 50 leads"
echo "  [ ] Save to: tog_leads.csv"
echo ""
echo "STEP 2: Instantly.ai (Email Automation)"
echo "  [ ] Go to https://instantly.ai"
echo "  [ ] Sign up for Starter plan (/mo)"
echo "  [ ] Connect your Gmail: akennedy@theonegroup.info"
echo "  [ ] Verify domain"
echo ""
echo "STEP 3: Upload Leads"
echo "  [ ] Import tog_leads.csv to Instantly"
echo "  [ ] Map fields: first_name, company_name, email"
echo ""
echo "STEP 4: Create Campaign"
echo "  [ ] Create new campaign"
echo "  [ ] Name: 'TOG - Roofing July 2026'"
echo "  [ ] Upload leads"
echo "  [ ] Set daily limit: 20 emails/day"
echo ""
echo "STEP 5: Add Email Sequence"
echo "  [ ] Email 1: Copy from email_sequence.md (Day 0)"
echo "  [ ] Email 2: Copy from email_sequence.md (Day 2)"
echo "  [ ] Email 3: Copy from email_sequence.md (Day 5)"
echo "  [ ] Email 4: Copy from email_sequence.md (Day 10)"
echo "  [ ] Email 5: Copy from email_sequence.md (Day 14)"
echo "  [ ] Add delays between emails"
echo ""
echo "STEP 6: Launch"
echo "  [ ] Review all emails"
echo "  [ ] Test send to yourself"
echo "  [ ] ACTIVATE campaign"
echo "  [ ] Set calendar reminder to check replies daily"
echo ""
echo "STEP 7: Track"
echo "  [ ] Create Google Sheet: 'TOG Campaign Tracking'"
echo "  [ ] Columns: Company | Contact | Date | Status | Notes"
echo ""
echo "==================================="
echo "Expected Timeline:"
echo "- Setup: 1 hour"
echo "- First emails: Within 24 hours"
echo "- First replies: Day 2-3"
echo "- First meeting: Week 1"
echo "- First close: Week 2-3"
echo "==================================="
